spring.application.name=kokoro
# H2コンソールを使えるようにする
spring.h2.console.enabled=true
# DBの接続設定（メモリ上に保存する設定です）
spring.datasource.url=jdbc:h2:file:./data/sampledb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# テーブルを自動作成する設定
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
